# Problem 14
# https://projecteuler.net/problem=14

def collatz(n):

    seq_len = 1

    while n != 1:
        seq_len += 1
        if n % 2 == 0:
            n /= 2
        else:
            n = 3*n + 1

    return seq_len


def longest_cseq():
    
    info = [0, 0]
    for i in range(1, 1000000):
        c = collatz(i)
        if c > info[1]:
            info[0], info[1] = i, c

    print ("The largest seq is generated by: {} and the length is: {}\n".format(info[0], info[1]))


if __name__ == "__main__":

    print ("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print ("|          Problem 14           |")
    print ("|         Andrew Wilson         |")
    print ("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n")
    
    longest_cseq()
